modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Ketok4321/wilderness/issues"
license = "GNU LGPL v3"

[[mods]]
modId = "wilderness"
version = "${version}"
displayName = "Wilderness"
authors = "Ketok"
description = '''
Wilderness enhances minecraft's forests by adding new, wilder variants of them
'''
logoFile = "assets/wilderness/icon.png"

[[dependencies.wilderness]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wilderness]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wilderness]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wilderness]]
modId = "terrablender"
mandatory = true
versionRange = "[3,)"
ordering = "AFTER"
side = "BOTH"
